### ISSUE TITLE
Enabling the plugin by default

### ISSUE THREAD

**Issue by jan-warchol** [Carpetsmoker/auto_autoread.vim#3]
Hi,

I have installed your plugin using [vim-plug](https://github.com/junegunn/vim-plug), and I can enable it by issuing `:Autoread` command inside vim. However, I would just like to have it enabled by default. I tried simply adding this command to my `.vimrc`, like this:

```
call plug#begin('~/.vim/plugged')
Plug 'Carpetsmoker/auto_autoread.vim'
call plug#end()

Autoread 1
```

but the plugins are loaded after `.vimrc` and I'm getting this:

```
Error detected while processing /home/codilime/.vimrc:
line   14:
E492: Not an editor command: Autoread 1
```

Can you change plugin code so that it will be enabled by default? Personally I find the need to enable it after installing quite confusing.

**Comment by Carpetsmoker** [comment]
It should be enabled by default, but I would expect plugins to not be loaded until after the vimrc has been loaded? I don't know how vim-plug works.

At any rate, adding it to your vimrc file like that makes little sense, since there is no actual file to watch. You'll probably want to use an autocommand. (e.g. `FileReadPost` or some such).
